robot_cfg:
  kinematics:
    use_usd_kinematics: False
    usd_path: null
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/ur5/ur5.urdf"
    asset_root_path: "robot/ur5"
    
    base_link: "base_link"
    ee_link: "tool0"
    link_names: null
    lock_joints: null
    extra_links: null

    
    collision_link_names: ['shoulder_link','upper_arm_link', 'forearm_link', 'wrist_1_link', 
    'wrist_2_link' ,'wrist_3_link', 'tool0'] # List[str]
    collision_spheres:
      shoulder_link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
      upper_arm_link:
        - "center": [-0.0, 0.0, 0.129]
          "radius": 0.06
        - "center": [-0.418, 0.002, 0.135]
          "radius": 0.06
        - "center": [-0.104, 0.001, 0.131]
          "radius": 0.06
        - "center": [-0.209, 0.001, 0.132]
          "radius": 0.06
        - "center": [-0.313, 0.002, 0.134]
          "radius": 0.06
      forearm_link:
        - "center": [-0.0, 0.0, 0.039]
          "radius": 0.06
        - "center": [-0.374, -0.014, 0.014]
          "radius": 0.06
        - "center": [-0.094, -0.004, 0.033]
          "radius": 0.06
        - "center": [-0.187, -0.007, 0.026]
          "radius": 0.06
        - "center": [-0.281, -0.011, 0.02]
          "radius": 0.06
      wrist_1_link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
      wrist_2_link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.04
      wrist_3_link:
        - "center": [0.0, -0.0, -0.025]
          "radius": 0.04
      tool0:
          - "center": [0.001, 0.001, 0.05]
            "radius": -0.01 #0.05


    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    self_collision_ignore: {
      "shoulder_link": ["tool0"],
      "upper_arm_link": ["forearm_link", "shoulder_link", "tool0"],
      "forearm_link": ["wrist_1_link", "wrist_2_link", "wrist_3_link"],
      "wrist_1_link": ["wrist_2_link","wrist_3_link","tool0"],
      "wrist_2_link": ["wrist_3_link", "tool0"],
      "wrist_3_link": ["tool0"],
      }
    self_collision_buffer: {'upper_arm_link': 0, 
      'forearm_link': 0, 
      'wrist_1_link': 0, 
      'wrist_2_link': 0,
      'wrist_3_link' : 0,
      'tool0': 0.025,
      } 
      
    use_global_cumul: True
    mesh_link_names:  ['shoulder_link','upper_arm_link', 'forearm_link', 'wrist_1_link', 
    'wrist_2_link' ,'wrist_3_link'] # List[str]

    cspace:
      joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
      retract_config:  [0.0, -2.2, 1.9, -1.383, -1.57, 0.00]
      null_space_weight:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.1
